Repository openMetadataInitiative/openMINDS, pull requests merged in 2025-01, with the labels that each got.

#36 Generation of changelogs.
  build.py
  openMINDS_pipeline/constants.py
  openMINDS_pipeline/models.py
  openMINDS_pipeline/resolver.py
  openMINDS_pipeline/schema_comparator.py
  openMINDS_pipeline/utils.py
  openMINDS_pipeline/vocab.py
Labels: enhancement

#40 logo and readme update
  README.md
  img/openMINDS_logo_dark.png
  img/openMINDS_logo_dark.svg
  img/openMINDS_logo_light.png
  img/openMINDS_logo_light.svg
Labels: documentation

#41 Update versions.json
  versions-dev.json
  versions.json
Labels: bug

#43 Update vocab.py
  openMINDS_pipeline/vocab.py
Labels: bug
