Repository openMetadataInitiative/openMINDS, pull requests merged in 2025-09, with the labels that each got.

#80 Exclude '.git' from rsync deletion process.
  .github/workflows/build-dev.yml
  .github/workflows/build.yml
Labels: bug

#61 Change Neurostars link
  README.md
Labels: docu

#79 Add new line character at the end of the changelog (JSON file).
  openMINDS_pipeline/utils.py
Labels: enhancement
